### ISSUE TITLE
[Framework] Check for special characters in adduser command

### ISSUE THREAD

**Issue by profiluefter** [Teamspeak-Query-Plugin-Framework/tsq-plugin-framework#46]
**Describe the bug**
If you put special characters, like the ';' separator used, in the username in the adduser command, you'll get a NullPointerException. I'm not saying that this is an problem(a person that want's to do this deserves an error), but it could be handled better.

**To Reproduce**
1. Run the software and get it to a working state
2. Run the `adduser` command
3. Enter an username with a ';' in it. e.g. `admin;something`
4. Enter a password twice
5. Try to login with the account created. e.g `admin`

**Expected behavior**
The adduser command should either fail when given a special character or the character should be escaped.

**Logs or Screenshots**
`Exception in thread "Thread-0" java.lang.NullPointerException
        at net.vortexdata.tsqpf.console.ConsoleHandler.run(ConsoleHandler.java:136)
        at java.lang.Thread.run(Thread.java:748)`
NullPointerException is triggered, because of a return value in [UserManager.java:194](https://github.com/Teamspeak-Query-Plugin-Framework/tsq-plugin-framework/blob/a05091f4450f6e4fc29fd20291613c19977d816f/src/main/java/net/vortexdata/tsqpf/authenticator/UserManager.java#L194).

**Comment by Vortexdata** [comment]
Fixed with #50.
