### ISSUE TITLE
Add framework and plugins command

### ISSUE THREAD

**Issue by Vortexdata** [Teamspeak-Query-Plugin-Framework/tsq-plugin-framework#53]
With this update, two new commands should be implemented:

### framework
- no parameter: Shows syntax
- reload: Reloads the whole framework, including configs, plugins, etc...
- stop / exit / shutdown: Shuts down the framework.
- kill: Kills the framework.
- stats: returns a overview of the frameworks hardware usage, prozess status and etc.

### plugins
- no parameter: Shows a list of all plugins and their status.
- reload: Reloads all plugins and their configuration.
- find <pluginname>: Return details of the desired plugin
- disable <pluginname>: Will disable the desired plugin

**Comment by TAXSET** [comment]
Using branch _v2.0-framework-plugin-commands_, some code is already implemented.
